
services:
  db:
    image: postgres:15-alpine
    container_name: meeting_db
    environment:
      POSTGRES_USER: meeting_user
      POSTGRES_PASSWORD: meeting_password
      POSTGRES_DB: meeting_db
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
